logging:
  level:
    root: INFO
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:app;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
    username: sa
    password: ''
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/migration/s.sql